spring.application.name=banco

# ===============================
# Configuracion del Servidor
# ===============================
server.port=8080

# ===============================
# Configuracion de Base de Datos H2
# ===============================
spring.datasource.url=jdbc:h2:mem:pascualbravodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# Configuracion de JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# "update" actualiza el esquema automaticamente sin borrar los datos al reiniciar
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola (Excelente para que el estudiante aprenda)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Consola Web de H2
# ===============================
# Permite a los estudiantes entrar a http://localhost:8080/h2-console para ver la BD
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
